version: "3.9"

services:
  db-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  web-service:
    build: . #Le Dockerfile doit être
    depends_on:
      db-service:
        condition: service_healthy
    volumes:
      - ./web-data:/var/www/html
    networks:
      - app-net
    environment:   #afin de pouvoir se connecter à la base de données et lire les variables d'environnement
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx-reverse-conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web-service
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge